name: Deploy jobs42

on:
    push:
        branches: [ main ]

jobs:
    deploy:
        runs-on: ubuntu-latest
        steps:
            - name: bring the code
              uses: actions/checkout@v6
            
            - name: install docker
              uses: docker/build-push-action@v7

            - name: docker build
              run: docker build -t jobs42:latest .

            - name: docker tag
              run: docker tag jobs42:latest europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}
            
            - name: gcloud auth
              uses: 'google-github-actions/auth@v2'
              with:
                credentials_json: '${{ secrets.GCLOUD_SERVICE_ACCOUNT }}'
            
            - name: docker login
              run: gcloud auth configure-docker europe-central2-docker.pkg.dev

            - name: docker push
              run: docker push europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}
            
            - name: kubernetes install
              run: gcloud components install gke-gcloud-auth-plugin
            
            - name: cluster credentials
              run: gcloud container clusters get-credentials klaster --location=europe-central2

            - name: kubernetes rollout new version
              run: kubectl set image deploy/jobs42 jobs42=europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}
