name: deploy jobs42

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - name: checkout repo
        uses: actions/checkout@v6
      
      - name: build docker image
        uses: docker/build-push-action@v7

      - run: docker build -t jobs42:latest .
      - run: docker tag jobs42:latest europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}


      - name: setup gcloud
        uses: google-github-actions/auth@v2
        with:
          project_id: 'helpful-brand-400112'
          credentials_json: ${{ secrets.GCLOUD_SERVICE_FILE }}

      - name: configure docker registry
        uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'
      
      - run: gcloud auth configure-docker europe-central2-docker.pkg.dev

      - name: push built image
        run: docker push europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}

      - name: install kubectl
        run: gcloud components install gke-gcloud-auth-plugin
      
      - name: get cluster credentials
        run: gcloud container clusters get-credentials klaster --location=europe-central2

      - name: deploy new image to cluster
        run: kubectl set image deploy/jobs42 europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }}