name: deploy jobs42

on:
  push:
    branches: [main]

jobs:
  build-and-push:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v6
      - uses: docker/build-push-action@v7

      - run: docker build -t europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }} .

      - uses: google-github-actions/auth@v2
        with:
          project_id: 'helpful-brand-400112'
          credentials_json: ${{ secrets.GCLOUD_SERVICE_FILE }}
      - uses: 'google-github-actions/setup-gcloud@v3'
        with:
          version: '>= 363.0.0'
      - run: ' gcloud auth configure-docker europe-central2-docker.pkg.dev'

      - run: docker push docker build -t europe-central2-docker.pkg.dev/helpful-brand-400112/job42/binary:${{ github.sha }} .
